# Generated by Django 2.1.1 on 2018-10-21 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlyZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl_max', models.FloatField()),
                ('altitude_msl_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GpsPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_height', models.FloatField()),
                ('cylinder_radius', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderedBoundaryPts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(db_index=True)),
                ('fly_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.FlyZone')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedWayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl', models.FloatField(default=200.0, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UasMission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='orderedwaypoint',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission'),
        ),
        migrations.AddField(
            model_name='obstacles',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission'),
        ),
        migrations.AddField(
            model_name='gpsposition',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission'),
        ),
        migrations.AddField(
            model_name='flyzone',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedwaypoint',
            unique_together={('mission', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='orderedboundarypts',
            unique_together={('order', 'fly_zone')},
        ),
    ]
