# Generated by Django 3.1.5 on 2021-01-23 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('session_id', models.CharField(blank=True, max_length=256)),
                ('expires', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Connected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FlyZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl_max', models.FloatField()),
                ('altitude_msl_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GpsPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SearchGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=None, unique=True)),
                ('username', models.CharField(blank=True, max_length=256)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('university', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UasTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='interop.team',
                                           to_field='team_id')),
                ('gps', models.OneToOneField(to='interop.gpsposition', to_field='id', on_delete=django.db.models.deletion.CASCADE)),
                ('altitude_msl', models.FloatField()),
                ('uas_heading', models.FloatField()),
                ('uploaded', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UasMission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
                ('airdrop_pos',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airdrop_pos',
                                   to='interop.gpsposition')),
                ('emergent_last_known_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                              related_name='emergent_last_known_pos',
                                                              to='interop.gpsposition')),
                ('flyzone',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.flyzone')),
                ('off_axis_odlc_pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='off_axis_odlc_pos', to='interop.gpsposition')),
                ('search_grid',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.searchgrid')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_height', models.FloatField()),
                ('cylinder_radius', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='interop.uasmission')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedWayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl', models.FloatField(default=200.0, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.uasmission')),
            ],
            options={
                'unique_together': {('mission', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OrderedSearchGridPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(db_index=True)),
                (
                'search_grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.searchgrid')),
            ],
            options={
                'unique_together': {('order', 'search_grid')},
            },
        ),
        migrations.CreateModel(
            name='OrderedBoundaryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(db_index=True)),
                ('fly_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.flyzone')),
            ],
            options={
                'unique_together': {('order', 'fly_zone')},
            },
        ),
    ]
