# Generated by Django 2.1.3 on 2018-12-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0003_connected_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBoundaryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedSearchGridPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_msl', models.FloatField(default=200.0, null=True)),
                ('order', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Obstacles',
            new_name='Obstacle',
        ),
        migrations.RenameModel(
            old_name='Telemetry',
            new_name='UasTelemetry',
        ),
        migrations.AlterUniqueTogether(
            name='orderedboundarypts',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderedboundarypts',
            name='fly_zone',
        ),
        migrations.RemoveField(
            model_name='orderedboundarypts',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='flyzone',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='gpsposition',
            name='mission',
        ),
        migrations.AddField(
            model_name='uasmission',
            name='airdrop_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airdrop_pos', to='interop.GpsPosition'),
        ),
        migrations.AddField(
            model_name='uasmission',
            name='emergent_last_known_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergent_last_known_pos', to='interop.GpsPosition'),
        ),
        migrations.AddField(
            model_name='uasmission',
            name='flyzone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.FlyZone'),
        ),
        migrations.AddField(
            model_name='uasmission',
            name='home_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_pos', to='interop.GpsPosition'),
        ),
        migrations.AddField(
            model_name='uasmission',
            name='off_axis_odlc_pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_axis_odlc_pos', to='interop.GpsPosition'),
        ),
        migrations.DeleteModel(
            name='OrderedBoundaryPts',
        ),
        migrations.AddField(
            model_name='orderedsearchgridpoint',
            name='search_grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.SearchGrid'),
        ),
        migrations.AddField(
            model_name='orderedboundarypoint',
            name='fly_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.FlyZone'),
        ),
        migrations.AddField(
            model_name='uasmission',
            name='search_grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.SearchGrid'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedsearchgridpoint',
            unique_together={('order', 'search_grid')},
        ),
        migrations.AlterUniqueTogether(
            name='orderedboundarypoint',
            unique_together={('order', 'fly_zone')},
        ),
    ]
