# Generated by Django 2.1.3 on 2018-12-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0004_auto_20181215_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
