# Generated by Django 2.1.4 on 2018-12-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0005_clientsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='uastelemetry',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
