# Generated by Django 2.1.4 on 2019-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0006_uastelemetry_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsession',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='port',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='session_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='clientsession',
            name='username',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
