# Generated by Django 2.2.5 on 2019-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0009_auto_20190519_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAircraftTelemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_msl', models.FloatField()),
                ('uas_heading', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
