# Generated by Django 2.2.5 on 2020-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0009_auto_20190519_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='uastelemetry',
            name='team_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
