# Generated by Django 2.2.5 on 2020-10-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0010_auto_20201020_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='teams',
            name='team_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='teams',
            name='university',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='teams',
            name='username',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='uastelemetry',
            name='team_id',
            field=models.IntegerField(default=None),
        ),
    ]
