# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash docker-compose

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build --parallel
    - docker-compose run backend python manage.py migrate

Test Frontend:
  stage: test
  tags:
    - docker
  script:
    - docker-compose build --parallel
    - docker-compose run frontend npm test
    - docker-compose run frontend npm run coverage
  artifacts:
    expire_in: 1 week
    paths:
      - frontend/coverage/

Test Backend:
  stage: test
  tags:
    - docker
  script:
    - docker-compose build --parallel
    - docker-compose run backend coverage run --source='.' manage.py test
    - docker-compose run backend coverage report
    - docker-compose run backend coverage html
  artifacts:
    expire_in: 1 week
    paths:
      - htmlcov/

Final:
  stage: deploy
  script:
  - echo "Done!"
  when: on_success
