# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash

  # Prep docker-compose stuff
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

variables:
  LC_ALL: 'C.UTF-8'
  LANG: 'C.UTF-8'
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build & Push:
  stage: build
  tags:
    - docker
  script:
    - ./tools/setup-ci.sh
    - docker-compose build --parallel
    - docker-compose run django python manage.py migrate

Test Frontend:
  stage: test
  tags:
    - docker
  script:
    - ./tools/setup-ci.sh
    - docker-compose build --parallel
    - docker-compose run npm npm test
    - docker-compose run npm npm run coverage
  artifacts:
    expire_in: 1 week
    paths:
      - frontend/coverage/

Test Backend:
  stage: test
  tags:
    - docker
  script:
    - ./tools/setup-ci.sh
    - docker-compose build --parallel
    - docker-compose run django coverage run --source='.' manage.py test
    - docker-compose run django coverage report
    - docker-compose run django coverage html
  artifacts:
    expire_in: 1 week
    paths:
      - htmlcov/

Final:
  stage: deploy
  script:
  - echo "Done!"
  when: on_success
