version: "3"

services:
  ### This is for development purposes ONLY ###
  ### And should not be in prod ###
  interop-db:
    container_name: interop-db
    hostname: interop-db
    image: postgres
    environment:
      - POSTGRES_DB=auvsi_suas_db
    networks:
      interopnet:
        ipv4_address: 172.170.0.76

  ### This is for development purposes ONLY ###
  ### And should not be in prod ###
  interop_server:
    container_name: interop-server
    hostname: interop-server
    image: auvsisuas/interop-server:latest
    ports:
      - "8000:80"
    depends_on:
      - interop-db
    links:
      - interop-db
    networks:
      uasnet:
        ipv4_address: 172.0.0.77
      interopnet:
        ipv4_address: 172.170.0.77

  nginx:
    container_name: gcomx-nginx
    hostname: gcomx-nginx
    build:
      context: ./nginx
    volumes:
      - .:/uas/gcomx/nginx
    ports:
      - "8089:80"
    networks:
      uasnet:
        ipv4_address: 172.0.0.6

  db:
    container_name: gcomx-db
    hostname: gcomx-db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      uasnet:
        ipv4_address: 172.0.0.5

  redis:
    container_name: gcomx-redis
    hostname: gcomx-redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      uasnet:
        ipv4_address: 172.0.0.4

  npm:
    container_name: gcomx-npm
    hostname: gcomx-npm
    build:
      context: ./frontend
    image: gcomx_frontend_image
    command: [ "npm", "run", "start" ]
    volumes:
      - ./frontend:/uas/gcomx/frontend
      - /uas/gcomx/frontend/node_modules
    working_dir: /uas/gcomx/frontend
    ports:
      - "3000:3000"
    networks:
      uasnet:
        ipv4_address: 172.0.0.3

  django:
    container_name: gcomx-django
    hostname: gcomx-django
    build:
      context: ./backend
    image: gcomx_server_image
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8080" ]
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/uas/gcomx/api
      - ./frontend:/uas/gcomx/api/frontend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - npm
      - redis
    networks:
      uasnet:
        ipv4_address: 172.0.0.2

networks:
  uasnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
  interopnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.170.0.0/16
