# Generated by Django 3.1.5 on 2021-01-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedRouteWayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl', models.FloatField(default=200.0, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('delay', models.IntegerField(default=0)),
                ('is_generated', models.BooleanField()),
                ('wp_type', models.CharField(choices=[('none', 'none'), ('auto_flight', 'auto_flight'), ('airdrop', 'airdrop'), ('search_grid', 'search_grid'), ('off_axis', 'off_axis')], default='none', max_length=128)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.uasmission')),
            ],
            options={
                'unique_together': {('mission', 'order')},
            },
        ),
    ]
