# Generated by Django 2.1.2 on 2018-11-03 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interop', '0002_auto_20181021_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedRouteWayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude_msl', models.FloatField(default=200.0, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('is_generated', models.BooleanField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderedroutewaypoint',
            unique_together={('mission', 'order')},
        ),
    ]
