# Generated by Django 2.1.4 on 2019-01-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedroutewaypoint',
            name='wp_type',
            field=models.CharField(choices=[('none', 'none'), ('auto_flight', 'auto_flight'), ('airdrop', 'airdrop'), ('search_grid', 'search_grid'), ('off_axis', 'off_axis')], default='none', max_length=128),
        ),
    ]
