# Generated by Django 2.2.2 on 2019-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoidance', '0002_orderedroutewaypoint_wp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedroutewaypoint',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
