# Generated by Django 2.2.5 on 2019-11-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imp_module', '0006_impimage_yaw'),
        ('interop', '0009_auto_20190519_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imp_module.ImpImage')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interop.UasMission')),
            ],
        ),
    ]
