# Generated by Django 2.1.3 on 2018-11-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', unique=True)),
                ('processed_flag', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('altitude', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('heading', models.IntegerField(default=0)),
                ('width', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('height', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ImpODLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('type', models.TextField(blank=True, default='')),
                ('shape', models.TextField(blank=True, default='')),
                ('background_color', models.TextField(blank=True, default='')),
                ('alphanumeric', models.TextField(blank=True, default='')),
                ('alphanumeric_color', models.TextField(blank=True, default='')),
                ('orientation', models.TextField(blank=True, default='')),
                ('image_source', models.TextField(default='')),
                ('x', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('y', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('w', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
                ('h', models.DecimalField(decimal_places=5, default=0, max_digits=6)),
            ],
        ),
    ]
