# Generated by Django 2.1.4 on 2019-01-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impodlc',
            name='auvsi_id',
            field=models.IntegerField(null=True),
        ),
    ]
