# Generated by Django 2.1.7 on 2019-04-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0002_impodlc_auvsi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='impimage',
            name='width',
        ),
        migrations.AddField(
            model_name='impodlc',
            name='image_source_model',
            field=models.ForeignKey(null=True, on_delete=None, to='imp_module.ImpImage'),
        ),
    ]
