# Generated by Django 2.2.2 on 2019-06-08 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0004_impimage_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='impodlc',
            name='latitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=0, max_digits=11), default=list, size=None),
        ),
        migrations.AddField(
            model_name='impodlc',
            name='longitudes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, default=0, max_digits=11), default=list, size=None),
        ),
        migrations.AddField(
            model_name='impodlc',
            name='orientationAbss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, default=0, max_digits=7), default=list, size=None),
        ),
    ]
