# Generated by Django 2.2.5 on 2019-10-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0005_auto_20190608_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='impimage',
            name='yaw',
            field=models.FloatField(default=0),
        ),
    ]
