# Generated by Django 2.2.5 on 2020-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0006_impimage_yaw'),
    ]

    operations = [
        migrations.AddField(
            model_name='impimage',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
