# Generated by Django 2.2.5 on 2020-10-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imp_module', '0007_impimage_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impimage',
            name='team',
        ),
    ]
